### ISSUE TITLE
RobotPoseEstimator qui utilise le gyro, les encodeurs et PhotonVision

### ISSUE THREAD

**Issue by Adibou16** [Ultime5528/FRC2023#18]
Exemple : https://docs.photonvision.org/en/latest/docs/examples/simposeest.html

On veut garder dans le Drivetrain une Pose2d absolue, qui ne se reset jamais.

**Comment by etiennebeaulac** [comment]
@Adibou16 Trouvé!

```
robotpy_apriltag.loadAprilTagLayoutField(robotpy_apriltag.AprilTagField.k2023ChargedUp)
```

https://robotpy.readthedocs.io/projects/apriltag/en/stable/robotpy_apriltag/functions.html
