### ISSUE TITLE
Tester robotpy_apriltag

### ISSUE THREAD

**Issue by etiennebeaulac** [Ultime5528/FRC2023#2]
https://robotpy.readthedocs.io/projects/apriltag/en/stable/robotpy_apriltag.html

- [x] Détecter un tag sur une image fixe
- [x] Détecter un tag sur une VideoCapture
- [x] Trouver les paramètres de la caméra (fx, dy, cx, cy)
- [ ] Trouver la position de la caméra par rapport à un tag

**Comment by ThomasMcDonald904** [comment]
We will use photonvision instead
